{% set name = "datatable" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datatable-{{ version }}.tar.gz
  sha256: 8a9f6953ef6b02ede3d7c490f17d5c18c9b1bf2d58dd5451a8cac40ed887d775

build:
  number: 0
  # Not compatible with linux-s390x and the python build system fails on Windows:
  #   File "C:\b\abs_34334ddqln\croot\datatable_1704920393290\work\ci\ext.py", line 247, in build_extension
  #     ext.compiler.add_include_dir(ext.compiler.path + "\\include")
  # AttributeError: 'Compiler' object has no attribute 'path'
  skip: true  # [py<36 or s390x or win]
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation -C reuse_version=1

# numpy and pandas are _optional_ dependencies of dataframe
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - datatable
  files:
    - setup.cfg
  source_files:
    - src
    - tests
    - tests_random
    - LICENSE
  commands:
    - pip check
    - rm tests/test-docs.py
    # Skipping test_random_attack because it requires files that are not part of sdist (tests_random/methods)
    - pytest -vv tests -k 'not test_fread_from_cmd2 and not test_random_attack and not test_dt_version'
  requires:
    - pip
    - numpy
    - pandas
    - xlrd
    - pytest >=3.1
    - pytest-cov
    - docutils >=0.14

about:
  home: https://github.com/h2oai/datatable
  summary: A Python package for manipulating 2-dimensional tabular data structures.
  description: |-
    This is a Python package for manipulating 2-dimensional tabular data
    structures (aka data frames). It is close in spirit to pandas or SFrame;
    however we put specific emphasis on speed and big data support. As the name
    suggests, the package is closely related to R's data.table and attempts
    to mimic its core algorithms and API.
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  dev_url: https://github.com/h2oai/datatable
  doc_url: https://datatable.readthedocs.io

extra:
  skip-lints:
    - missing_wheel
  recipe-maintainers:
    - JeanChristopheMorinPerso
